name: Deploy Frontend to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to production server
        env:
          SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "SSH_KEY value: $SSH_KEY"
          # Continue with your deployment steps using $SSH_KEY
          
      - name: Deploy to production server
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
          SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # Create .ssh directory
          mkdir -p ~/.ssh
          
          # Add the SSH key
          echo "${SSH_KEY}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          cat ~/.ssh/deploy_key
