name: Deploy Frontend to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup SSH
        env:
          SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "${SSH_KEY}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          # Add www.manoskarystinos.com SSH key to known_hosts
          ssh-keyscan -H www.manoskarystinos.com >> ~/.ssh/known_hosts

      - name: Debug SSH connection
        run: |
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no www.manoskarystinos.com 'echo "SSH connection successful"'

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "20.10.0"

      - name: Install dependencies
        run: npm install

      - name: Build the frontend
        run: npm run build

      - name: Deploy to production server
        env:
          SSH_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          # Sync the build directory to the server
          rsync -e "ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no" -avz --delete ./build/ www.manoskarystinos.com:/var/www/manos-movies/movies-backend/frontend_build

          # Restart uWSGI
          ssh -i ~/.ssh/deploy_key -o StrictHostKeyChecking=no www.manoskarystinos.com 'sudo systemctl restart uwsgi'
